// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.IronDoc.Tests.Fakes")]
[assembly: AssemblyProductAttribute("Plainion.IronDoc")]
[assembly: AssemblyDescriptionAttribute("Plainion.IronDoc")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("2.2.0")]
[assembly: AssemblyFileVersionAttribute("2.2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.IronDoc.Tests.Fakes";
        internal const System.String AssemblyProduct = "Plainion.IronDoc";
        internal const System.String AssemblyDescription = "Plainion.IronDoc";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "2.2.0";
        internal const System.String AssemblyFileVersion = "2.2.0";
    }
}
