// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.IronDoc")>]
[<assembly: AssemblyProductAttribute("Plainion.IronDoc")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.IronDoc")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2017")>]
[<assembly: AssemblyVersionAttribute("2.5.0")>]
[<assembly: AssemblyFileVersionAttribute("2.5.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.IronDoc"
    let [<Literal>] AssemblyProduct = "Plainion.IronDoc"
    let [<Literal>] AssemblyDescription = "Plainion.IronDoc"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2017"
    let [<Literal>] AssemblyVersion = "2.5.0"
    let [<Literal>] AssemblyFileVersion = "2.5.0"
